version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: manlo_postgres
    restart: always
    environment:
      POSTGRES_USER: manlo
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: manlo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
